#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pry-byebug'
require_relative '../lib/me_not_whitespace'

BASE_REF = ENV['BASE_REF']
HEAD_REF = ENV['HEAD_REF']

FILE_TYPE = 'file'
TRAILING_WHITESPACE_REGEX = /\s+$/

def modified_file_paths(base_ref, head_ref)
  `git diff "#{base_ref}..#{head_ref}" --name-only`
    .split("\n")
end

def validate_files(file_paths)
  result = true

  file_paths.each do |file_path|
    next unless File.ftype(file_path) == FILE_TYPE

    result = false if File.readlines(file_path)
      .map(&:chomp)
      .select { |line| line.match? TRAILING_WHITESPACE_REGEX }
      .any?

    break unless result
  end

  result
end

file_paths = modified_file_paths(BASE_REF, HEAD_REF)

exit 1 unless validate_files(file_paths)
